on:
  push:
    branches:
      - "main"

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.build-publish.outputs.page_url }}
    steps:
     
    - uses: checkout@v4

    - id: build-publish
      uses: bitovi/github-actions-react-to-github-pages@v1.2.4
      with:
        path: dist